/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csci2320;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Scanner sc = new Scanner(System.in);
        String line = sc.nextLine();
        sc.close();

        int a = 5;
        Integer b = 7;
        int c = b;
    }
}
